### ISSUE TITLE
Design HTML

### ISSUE THREAD

**Issue by gauravarora011** [gauravarora011/fuelprice_api#1]
can someone design HTML page for the same

**Comment by pragya68** [comment]
Can consider

**Comment by gauravarora011** [comment]
@pragya68 Sounds Great.

**Comment by thakkardharmik** [comment]
@gauravarora011 Can I help here?

**Comment by gauravarora011** [comment]
You can simply enhance the one web page of the app.

**Comment by sooxt98** [comment]
Check pull request
